#define VIAL_KEYBOARD_UID {0x76, 0xE3, 0x82, 0x10, 0x38, 0xCA, 0x3C, 0xF0}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
