#define VIAL_KEYBOARD_UID {0xB5, 0xF8, 0x67, 0x0D, 0x51, 0x58, 0xA3, 0x4D}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 1
