/* SPDX-License-Identifier: GPL-2.0-or-later */
#define VIAL_KEYBOARD_UID {0xE5, 0x3F, 0x62, 0x5F, 0x94, 0x53, 0xD6, 0x1A}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
