#define VIAL_KEYBOARD_UID {0x42, 0xCD, 0x03, 0x61, 0xD1, 0xFE, 0x60, 0x38}

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 3
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
