#define VIAL_KEYBOARD_UID {0x07, 0x24, 0x1A, 0x84, 0x71, 0xE3, 0xDE, 0xA3}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4

