#define VIAL_KEYBOARD_UID {0xA9, 0xEA, 0x25, 0x0D, 0x22, 0x5D, 0xAA, 0xAB}

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
