#define VIAL_KEYBOARD_UID {0xC3, 0xFC, 0xA7, 0x89, 0x6F, 0x96, 0xA1, 0x5F}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
