#define VIAL_KEYBOARD_UID {0xB5, 0x8D, 0x12, 0x70, 0xC0, 0xFE, 0xA2, 0x00}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4