#define VIAL_KEYBOARD_UID {0xF4, 0x85, 0x24, 0xB0, 0x6F, 0x8D, 0x78, 0x7B}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
