#define VIAL_KEYBOARD_UID {0x84, 0x88, 0xDA, 0xE3, 0x43, 0xF5, 0x0E, 0x2A}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
