/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xB1, 0x08, 0xC8, 0x8C, 0xCF, 0x50, 0x31, 0x1F}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2
