#define VIAL_KEYBOARD_UID {0xD9, 0xDB, 0x72, 0x07, 0x7B, 0x6B, 0x5E, 0xF4}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
