#define VIAL_KEYBOARD_UID {0x7A, 0xF0, 0xA7, 0x9C, 0xC9, 0x92, 0x97, 0xEB}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
