#define VIAL_KEYBOARD_UID {0x29, 0x45, 0xCE, 0x03, 0x24, 0x8C, 0x2C, 0x0C}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
