#define VIAL_KEYBOARD_UID {0xC8, 0xEC, 0xD8, 0xCF, 0x43, 0x52, 0xBC, 0xAC}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
