#define VIAL_KEYBOARD_UID {0xB0, 0x2A, 0x89, 0x44, 0x1C, 0xB3, 0x2E, 0x37}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
