#define VIAL_KEYBOARD_UID {0xDD, 0x35, 0xC7, 0x6E, 0xE6, 0xC3, 0x98, 0x63}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 3
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 1
