/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x22, 0x12, 0x7C, 0xA4, 0xF4, 0x36, 0x63, 0x54}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 3

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
