#define VIAL_KEYBOARD_UID {0xBA, 0x5B, 0xC7, 0x18, 0x82, 0xB7, 0x30, 0xC9}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
