#define VIAL_KEYBOARD_UID {0x37, 0x29, 0x66, 0xAF, 0xA2, 0x49, 0x00, 0xDC}

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 0
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4

