#define VIAL_KEYBOARD_UID {0xE0, 0x7D, 0x62, 0xD6, 0x5A, 0xAB, 0x88, 0x83}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
