#define VIAL_KEYBOARD_UID {0x21, 0xEB, 0x6B, 0xD7, 0x16, 0xAE, 0x65, 0x09}

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 0
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 0
#define NO_MUSIC_MODE
