#define VIAL_KEYBOARD_UID {0x1E, 0x09, 0x09, 0xA1, 0x18, 0xB4, 0x15, 0xDB}

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 2
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2
