#pragma once

#define VIAL_KEYBOARD_UID { 0xFC, 0x16, 0x30, 0x20, 0xDA, 0x5F, 0xCA, 0xAD }
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 2

