#define VIAL_KEYBOARD_UID {0xF2, 0xCF, 0x1F, 0xE2, 0xC6, 0x6D, 0x1C, 0x5F}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
