#define VIAL_KEYBOARD_UID {0xF6, 0xF7, 0x43, 0xDB, 0x22, 0x01, 0x16, 0xD9}

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#define VIAL_TAP_DANCE_ENTRIES 1
#define VIAL_COMBO_ENTRIES 2
#define VIAL_KEY_OVERRIDE_ENTRIES 4
