#define VIAL_KEYBOARD_UID {0x4A, 0x9C, 0xB6, 0x1E, 0xF3, 0x73, 0xD4, 0xFA}

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
