#define VIAL_KEYBOARD_UID {0x93, 0x36, 0x50, 0xFC, 0xA3, 0xBF, 0x0E, 0x00}
#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 4


#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define VIAL_KEY_OVERRIDE_ENTRIES 4
